### ISSUE TITLE
Partnership

### ISSUE THREAD

**Issue by yubing24** [DancesportSoftware/das#18]
Partnership in DAS is a unique bond between two users who both have the Athlete role. 

Requirments for Partnership:
- [x] There is no limit on the number of partnership that a user can have
- [x] Only users with Athlete role can have a partnership with other users who have Athlete role
- [x] Two users can have at most two partnerships between them:
  - A as a Lead and B as a Follow, or
  - B as a Lead and A as a Follow
- [x] Partnership cannot be removed
- [x] An Athlete user must have a Partnership in order to compete at a Competition
- [x] Both lead and follow can select if the partnership is their own "favorite" partnership. Favorited partnerships will be listed at the top of partnership selection list during competition registration.

**Comment by yubing24** [comment]
Commit c4bd109 was supposed to be for issue #21 but mistakenly associated with this issue.

**Comment by yubing24** [comment]
Implemented.
