### ISSUE TITLE
Partnership Request Blacklist

### ISSUE THREAD

**Issue by yubing24** [DancesportSoftware/das#19]
**Motivation**
In case of a malicious user signed up an account, the malicious user can send spam requests to other users in the system and can cause problems. Partnership Request Blacklist can allow users to stop further partnership request spams

**Requirements**
- [ ] Only an Athlete user can have a Partnership Request Blacklist
- [ ] Only an Athlete user can be added to another Athlete user's Partnership Request Blacklist
- [ ] A blacklisted user can be whitelisted by the reporter
- [ ] A blacklisted user cannot send any Partnership Request to the user who blacklisted him/her
