### ISSUE TITLE
User Roles

### ISSUE THREAD

**Issue by yubing24** [DancesportSoftware/das#20]
All users of DAS should have an only have one account. Each account can have one or more roles.

Roles in DAS are:
- [ ] Athlete
- [ ] Adjudicator
- [ ] Scrutineer
- [ ] Organizer
- [ ] Deck Captain
- [ ] Emcee
- [ ] Administrator

**Requirements**
- [ ] Any anonymous user of DAS should be able to sign up an account in DAS. All account in DAS are created with a default Athlete role.
- [ ] Administrator account cannot be created through public-facing user interface. Administrator account can only be created by logging on the server and directly creating record in the database.
- [ ] Roles of Adjudicator, Scrutineer, and Organizers can only be provisioned by Administrator, through web services
- [ ] Once created, roles cannot be removed (even Administrator)
