### ISSUE TITLE
User Role Provision

### ISSUE THREAD

**Issue by yubing24** [DancesportSoftware/das#21]
Rules for User Role Provision
- [ ] All newly created accounts are automatically granted the role of Athlete
  - [ ] Athlete role cannot be provisioned by any user
  - [ ] User with Athlete-only role cannot provision any role
- [ ] Administrator role must not be created by web services
  - [ ] Administrator role can only be created through direct database operationg
- [ ] Adjudicator, Scrutineer, and Organizer can only be provisioned by an existing Administrator user
  - [ ] An application for each role must be submitted in order to have access to any of these roles
  - [ ] Application can be approved or denied by Administrator
    - [ ] If application is denied, user can still submit applications in the future for approval
  - [ ] Users with Adjudicator, Scutineer, and/or Organizer role cannot approve or deny applications for Adjudicator, Scrutineer, and/or Organizer roles
- [ ] Deck Captain and Emcee can be provisioned by an Administrator or Organizer
  - [ ] An application for each role must be submitted in order to have access to any of these roles
  - [ ] Application can be approved or denied by Administrator or Organizer
    - [ ] If application is denied, user can still submit applications in the future for approval
  - [ ] User with Adjudicator, Scrutineer, Deck Captain, and/or Emcee cannot approve or deny applications for Deck Captain or Emcee
- [ ] Adjudicator, Scrutineer, Organizer, Deck Captain can only access to data of the event and competition that they are appointed to.
- [ ] Emcee has read-access-only privildge to competition related data.
